apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: applicationmonitorings.applicationmonitoring.integreatly.org
spec:
  group: applicationmonitoring.integreatly.org
  names:
    kind: ApplicationMonitoring
    listKind: ApplicationMonitoringList
    plural: applicationmonitorings
    singular: applicationmonitoring
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["labelSelector"]
          properties:
            blackboxTargets:
              type: array
              items:
                type: object
                description: A target to be probed by the blackbox exporter
            labelSelector:
              type: string
              minimum: 1
              description: The selector used by the Prometheus and Grafana Operators to discover resources