apiVersion: v1
data:
  alertmanager.yaml: >-
    Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0Kcm91dGU6CiAgZ3JvdXBfd2FpdDogMzBzCiAgZ3JvdXBfaW50ZXJ2YWw6IDVtCiAgcmVwZWF0X2ludGVydmFsOiAxMmgKICByZWNlaXZlcjogZGVmYXVsdAogIHJvdXRlczoKICAtIG1hdGNoOgogICAgICBhbGVydG5hbWU6IERlYWRNYW5zU3dpdGNoCiAgICByZXBlYXRfaW50ZXJ2YWw6IDVtCiAgICByZWNlaXZlcjogZGVhZG1hbnNzd2l0Y2gKcmVjZWl2ZXJzOgotIG5hbWU6IGRlZmF1bHQKLSBuYW1lOiBkZWFkbWFuc3N3aXRjaAo=
kind: Secret
metadata:
  name: alertmanager-application-monitoring
  namespace: {{ .Namespace }}
  type: Opaque