apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-application-monitoring
  namespace: {{ .Namespace }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ .PrometheusRouteName }}"}}'